/**
 * 11月18日-11月23日 高雄/桃園 直飛東京機票與機加酒整合資料庫
 * Travel Dates: 2026/11/18 (Wed) - 2026/11/23 (Mon) [6 Days 5 Nights]
 */

export const TRAVEL_INFO = {
  departureDate: '2026-11-18',
  returnDate: '2026-11-23',
  durationDays: 6,
  durationNights: 5,
  season: '日本關東秋季紅葉賞楓旺季',
  lastUpdated: new Date().toISOString()
};

// 平台/來源定義
export const PLATFORMS = [
  { id: 'trip', name: 'Trip.com', color: '#0056b3', type: 'OTA' },
  { id: 'eztravel', name: '易遊網 ezTravel', color: '#e84118', type: 'OTA' },
  { id: 'agoda', name: 'Agoda 專案', color: '#8c7ae6', type: 'OTA' },
  { id: 'klook', name: 'Klook 旅遊', color: '#ff6b81', type: 'OTA' },
  { id: 'eva', name: '長榮航空官網', color: '#009432', type: 'Airline' },
  { id: 'ci', name: '中華航空官網', color: '#0652DD', type: 'Airline' },
  { id: 'starlux', name: '星宇航空官網', color: '#B33771', type: 'Airline' },
  { id: 'tiger', name: '台灣虎航官網', color: '#FFC312', type: 'LCC' },
  { id: 'peach', name: '樂桃航空官網', color: '#EA2027', type: 'LCC' },
  { id: 'jal', name: '日本航空 JAL 官網', color: '#273c75', type: 'Airline' },
  { id: 'ana', name: '全日空 ANA 官網', color: '#1289A7', type: 'Airline' }
];

// 東京交通方便熱門區域
export const CONVENIENT_AREAS = [
  { id: 'ueno', name: '上野 (Ueno)', desc: 'Skyliner直達、JR山手線樞紐', convenienceScore: 9.8 },
  { id: 'shinjuku', name: '新宿 (Shinjuku)', desc: '最大交通轉運站、購物美食無敵', convenienceScore: 9.9 },
  { id: 'ginza', name: '銀座/東銀座 (Ginza)', desc: '直達羽田成田地鐵、精品住宿', convenienceScore: 9.5 },
  { id: 'asakusa', name: '淺草 (Asakusa)', desc: '都營淺草線成田/羽田直達', convenienceScore: 9.2 },
  { id: 'ikebukuro', name: '池袋 (Ikebukuro)', desc: 'JR山手線大站、生活機能極佳', convenienceScore: 9.4 },
  { id: 'tokyo_station', name: '東京車站/丸之內', desc: '新幹線與JR中央線匯集地', convenienceScore: 9.7 },
  { id: 'shibuya', name: '澀谷 (Shibuya)', desc: '潮流中心、副都心線與JR交會', convenienceScore: 9.3 },
  { id: 'akihabara', name: '秋葉原 (Akihabara)', desc: 'JR山手線、日比谷線雙軌便利', convenienceScore: 9.1 }
];

// 純機票比較清單 (Round-trip Flights)
export const FLIGHT_DEALS = [
  {
    id: 'fl-001',
    type: 'flight',
    origin: 'KHH',
    originName: '高雄小港',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '台灣虎航 Tigerair',
    airlineCode: 'IT',
    isLCC: true,
    platform: 'tiger',
    platformName: '台灣虎航官網',
    price: 12800,
    originalPrice: 15500,
    outboundTime: '11/18 08:00 KHH ➔ 12:30 NRT (IT280)',
    inboundTime: '11/23 13:30 NRT ➔ 16:50 KHH (IT281)',
    flightTimeHours: 3.5,
    baggage: '包含 7kg 手提 + 20kg 託運行李',
    taxIncluded: true,
    seatClass: '經濟艙',
    rating: 8.2,
    directUrl: 'https://www.tigerairtw.com/zh-tw/',
    popularTag: '⚡ 高雄超值小資首選',
    isAlertTarget: true // < 17000
  },
  {
    id: 'fl-002',
    type: 'flight',
    origin: 'KHH',
    originName: '高雄小港',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '中華航空 China Airlines',
    airlineCode: 'CI',
    isLCC: false,
    platform: 'eztravel',
    platformName: '易遊網 ezTravel',
    price: 16800,
    originalPrice: 19200,
    outboundTime: '11/18 09:30 KHH ➔ 13:55 NRT (CI102)',
    inboundTime: '11/23 15:00 NRT ➔ 18:20 KHH (CI103)',
    flightTimeHours: 3.4,
    baggage: '包含 7kg 手提 + 23kg 託運行李 (附餐食)',
    taxIncluded: true,
    seatClass: '精緻經濟艙',
    rating: 8.9,
    directUrl: 'https://www.eztravel.com.tw/',
    popularTag: '🔥 華航高雄限時促銷',
    isAlertTarget: true // < 17000
  },
  {
    id: 'fl-003',
    type: 'flight',
    origin: 'KHH',
    originName: '高雄小港',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '長榮航空 EVA Air',
    airlineCode: 'BR',
    isLCC: false,
    platform: 'eva',
    platformName: '長榮航空官網',
    price: 18500,
    originalPrice: 21000,
    outboundTime: '11/18 07:00 KHH ➔ 11:25 NRT (BR108)',
    inboundTime: '11/23 12:25 NRT ➔ 15:45 KHH (BR107)',
    flightTimeHours: 3.4,
    baggage: '包含 7kg 手提 + 23kg 託運行李 (附餐食與視聽娛樂)',
    taxIncluded: true,
    seatClass: '標準經濟艙',
    rating: 9.1,
    directUrl: 'https://www.evaair.com/',
    popularTag: '早去午回',
    isAlertTarget: false
  },
  {
    id: 'fl-004',
    type: 'flight',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '台灣虎航 Tigerair',
    airlineCode: 'IT',
    isLCC: true,
    platform: 'trip',
    platformName: 'Trip.com',
    price: 11900,
    originalPrice: 14800,
    outboundTime: '11/18 06:35 TPE ➔ 10:45 NRT (IT200)',
    inboundTime: '11/23 11:45 NRT ➔ 15:00 TPE (IT201)',
    flightTimeHours: 3.1,
    baggage: '包含 7kg 手提 + 20kg 託運行李',
    taxIncluded: true,
    seatClass: '經濟艙',
    rating: 8.0,
    directUrl: 'https://tw.trip.com/',
    popularTag: '⚡ 桃機最低破萬價',
    isAlertTarget: true // < 17000
  },
  {
    id: 'fl-005',
    type: 'flight',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'HND',
    destinationName: '東京羽田',
    airline: '樂桃航空 Peach',
    airlineCode: 'MM',
    isLCC: true,
    platform: 'peach',
    platformName: '樂桃航空官網',
    price: 13500,
    originalPrice: 16200,
    outboundTime: '11/18 20:45 TPE ➔ 00:55+1 HND (MM860)',
    inboundTime: '11/23 05:55 HND ➔ 08:55 TPE (MM859)',
    flightTimeHours: 3.1,
    baggage: '包含 7kg 手提 + 20kg 託運行李',
    taxIncluded: true,
    seatClass: 'Value Peach',
    rating: 8.3,
    directUrl: 'https://www.flypeach.com/tw',
    popularTag: '羽田市區近直達',
    isAlertTarget: true // < 17000
  },
  {
    id: 'fl-006',
    type: 'flight',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '星宇航空 STARLUX',
    airlineCode: 'JX',
    isLCC: false,
    platform: 'starlux',
    platformName: '星宇航空官網',
    price: 16500,
    originalPrice: 19800,
    outboundTime: '11/18 08:30 TPE ➔ 12:45 NRT (JX800)',
    inboundTime: '11/23 14:00 NRT ➔ 17:05 TPE (JX801)',
    flightTimeHours: 3.2,
    baggage: '包含 7kg 手提 + 23kg 託運行李 (精緻機上餐與4K螢幕)',
    taxIncluded: true,
    seatClass: '限量特惠經濟艙',
    rating: 9.5,
    directUrl: 'https://www.starlux-airlines.com/',
    popularTag: '🌟 星宇楓葉季限時閃殺',
    isAlertTarget: true // < 17000
  },
  {
    id: 'fl-007',
    type: 'flight',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '長榮航空 EVA Air',
    airlineCode: 'BR',
    isLCC: false,
    platform: 'trip',
    platformName: 'Trip.com',
    price: 17800,
    originalPrice: 19800,
    outboundTime: '11/18 08:50 TPE ➔ 13:15 NRT (BR198)',
    inboundTime: '11/23 14:15 NRT ➔ 17:30 TPE (BR197)',
    flightTimeHours: 3.4,
    baggage: '包含 7kg 手提 + 23kg 託運行李',
    taxIncluded: true,
    seatClass: '經濟艙',
    rating: 9.1,
    directUrl: 'https://tw.trip.com/',
    popularTag: '長榮桃園經典熱門航班',
    isAlertTarget: false
  },
  {
    id: 'fl-008',
    type: 'flight',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'HND',
    destinationName: '東京羽田',
    airline: '日本航空 JAL',
    airlineCode: 'JL',
    isLCC: false,
    platform: 'jal',
    platformName: '日本航空 JAL 官網',
    price: 21500,
    originalPrice: 24500,
    outboundTime: '11/18 10:00 TPE ➔ 14:05 HND (JL098)',
    inboundTime: '11/23 18:15 HND ➔ 21:35 TPE (JL099)',
    flightTimeHours: 3.1,
    baggage: '包含 7kg 手提 + 2件23kg 託運行李(高額度)',
    taxIncluded: true,
    seatClass: '豪華經濟艙體驗',
    rating: 9.6,
    directUrl: 'https://www.jal.co.jp/tw/zh-tw/',
    popularTag: '👑 羽田松山/桃園旗艦款 46kg托運',
    isAlertTarget: false
  },
  {
    id: 'fl-009',
    type: 'flight',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'HND',
    destinationName: '東京羽田',
    airline: '全日空 ANA',
    airlineCode: 'NH',
    isLCC: false,
    platform: 'klook',
    platformName: 'Klook 旅遊',
    price: 20900,
    originalPrice: 23500,
    outboundTime: '11/18 13:30 TPE ➔ 17:45 HND (NH854)',
    inboundTime: '11/23 13:20 HND ➔ 16:15 TPE (NH853)',
    flightTimeHours: 3.2,
    baggage: '包含 7kg 手提 + 2件23kg 託運行李',
    taxIncluded: true,
    seatClass: '標準經濟艙',
    rating: 9.4,
    directUrl: 'https://www.klook.com/zh-TW/',
    popularTag: 'ANA五星航空優質體驗',
    isAlertTarget: false
  }
];

// 機加酒 (Flight + Hotel Package Deals)
export const PACKAGE_DEALS = [
  {
    id: 'pkg-001',
    type: 'package',
    origin: 'KHH',
    originName: '高雄小港',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '台灣虎航 Tigerair',
    platform: 'eztravel',
    platformName: '易遊網 ezTravel',
    price: 18900,
    originalPrice: 23800,
    hotelName: '兩國站塔 APA 飯店 (APA Hotel & Resort Ryogoku Eki Tower)',
    hotelArea: '淺草/兩國區',
    stationProximity: 'JR 兩國站 / 都營大江戶線 步行 3 分鐘 (成田/羽田直達捷運線)',
    isConvenientLocation: true,
    hotelRating: 8.4,
    hotelRatingText: '非常好 (8.4/10)',
    roomType: '高樓層標準雙人房 (含露天大浴場與晴空塔景觀)',
    breakfastIncluded: true,
    flightDetail: '11/18 08:00 高雄飛 ➔ 11/23 13:30 成田回',
    hotelImg: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    directUrl: 'https://www.eztravel.com.tw/',
    popularTag: '⚡ 機加酒降價通知符合標的！',
    isAlertTarget: true // Price 17000~27000, Rating >= 7.5, ConvenientLocation
  },
  {
    id: 'pkg-002',
    type: 'package',
    origin: 'KHH',
    originName: '高雄小港',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '中華航空 China Airlines',
    platform: 'trip',
    platformName: 'Trip.com',
    price: 19800,
    originalPrice: 25000,
    hotelName: '上野紅寶石飯店 (Hotel Sardonyx Ueno)',
    hotelArea: '上野 (Ueno)',
    stationProximity: 'JR 上野站 / 京成 Skyliner 上野站 步行 3 分鐘 (成田41分直達)',
    isConvenientLocation: true,
    hotelRating: 8.3,
    hotelRatingText: '非常好 (8.3/10)',
    roomType: '舒適雙人房 (附免費日式西式精緻早餐)',
    breakfastIncluded: true,
    flightDetail: '11/18 09:30 高雄飛 ➔ 11/23 15:00 成田回 (華航傳統航空托運)',
    hotelImg: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    directUrl: 'https://tw.trip.com/',
    popularTag: '⚡ 交通極優！成田Skyliner直達',
    isAlertTarget: true // Price 17000~27000, Rating >= 7.5, ConvenientLocation
  },
  {
    id: 'pkg-003',
    type: 'package',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '星宇航空 STARLUX',
    platform: 'klook',
    platformName: 'Klook 旅遊',
    price: 23500,
    originalPrice: 29800,
    hotelName: '新宿格拉斯麗飯店 (Hotel Gracery Shinjuku / 哥吉拉飯店)',
    hotelArea: '新宿 (Shinjuku)',
    stationProximity: 'JR 新宿站東口 / 西武新宿站 步行 3-5 分鐘',
    isConvenientLocation: true,
    hotelRating: 8.8,
    hotelRatingText: '極佳 (8.8/10)',
    roomType: '歌舞伎町高層景觀雙人房',
    breakfastIncluded: false,
    flightDetail: '11/18 08:30 桃園飛 ➔ 11/23 14:00 成田回 (星宇奢華服務)',
    hotelImg: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    directUrl: 'https://www.klook.com/zh-TW/',
    popularTag: '⚡ 星宇直飛 + 新宿哥吉拉名店！',
    isAlertTarget: true // Price 17000~27000, Rating >= 7.5, ConvenientLocation
  },
  {
    id: 'pkg-004',
    type: 'package',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '長榮航空 EVA Air',
    platform: 'eztravel',
    platformName: '易遊網 ezTravel',
    price: 25800,
    originalPrice: 32000,
    hotelName: '三井花園飯店銀座五丁目 (Mitsui Garden Hotel Ginza Gochome)',
    hotelArea: '銀座 (Ginza)',
    stationProximity: '地下鐵 東銀座站 步行 1 分鐘 / JR 有樂町站 步行 6 分鐘',
    isConvenientLocation: true,
    hotelRating: 8.9,
    hotelRatingText: '極佳 (8.9/10)',
    roomType: '摩登大床房 (附大浴場與溫泉體驗)',
    breakfastIncluded: true,
    flightDetail: '11/18 08:50 桃園飛 ➔ 11/23 14:15 成田回 (長榮正航班)',
    hotelImg: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
    directUrl: 'https://www.eztravel.com.tw/',
    popularTag: '⚡ 銀座精品時尚住宿！',
    isAlertTarget: true // Price 17000~27000, Rating >= 7.5, ConvenientLocation
  },
  {
    id: 'pkg-005',
    type: 'package',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'HND',
    destinationName: '東京羽田',
    airline: '樂桃航空 Peach',
    platform: 'agoda',
    platformName: 'Agoda 專案',
    price: 17500,
    originalPrice: 21500,
    hotelName: '池袋太陽城王子大飯店 (Sunshine City Prince Hotel Ikebukuro)',
    hotelArea: '池袋 (Ikebukuro)',
    stationProximity: 'JR 池袋站東口 步行 5 分鐘 / 地鐵東池袋站直達 3 分鐘',
    isConvenientLocation: true,
    hotelRating: 8.1,
    hotelRatingText: '很好 (8.1/10)',
    roomType: '太陽城高樓層景觀房',
    breakfastIncluded: false,
    flightDetail: '11/18 20:45 桃園飛 ➔ 11/23 05:55 羽田回',
    hotelImg: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
    directUrl: 'https://www.agoda.com/',
    popularTag: '⚡ 破盤價1.7萬起 入住池袋王子',
    isAlertTarget: true // Price 17000~27000, Rating >= 7.5, ConvenientLocation
  },
  {
    id: 'pkg-006',
    type: 'package',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'HND',
    destinationName: '東京羽田',
    airline: '日本航空 JAL',
    platform: 'trip',
    platformName: 'Trip.com',
    price: 26200,
    originalPrice: 33000,
    hotelName: '美滿如家飯店 東京站東 (MIMARU TOKYO STATION EAST)',
    hotelArea: '東京車站/茅場町',
    stationProximity: '地鐵 茅場町站 步行 2 分鐘 / JR 八丁堀站 步行 4 分鐘',
    isConvenientLocation: true,
    hotelRating: 9.2,
    hotelRatingText: '卓越 (9.2/10)',
    roomType: '日式公寓式大客房 (附廚房與微波爐小客廳)',
    breakfastIncluded: false,
    flightDetail: '11/18 10:00 桃園飛 ➔ 11/23 18:15 羽田回 (日航優質大席位)',
    hotelImg: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
    directUrl: 'https://tw.trip.com/',
    popularTag: '⚡ 9.2分高分家庭套房！羽田雙行李',
    isAlertTarget: true // Price 17000~27000, Rating >= 7.5, ConvenientLocation
  },
  {
    id: 'pkg-007',
    type: 'package',
    origin: 'TPE',
    originName: '桃園國際',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '長榮航空 EVA Air',
    platform: 'klook',
    platformName: 'Klook 旅遊',
    price: 29800,
    originalPrice: 36000,
    hotelName: '澀谷 STREAM 卓爾頓飯店 (Shibuya Stream Excel Hotel Tokyu)',
    hotelArea: '澀谷 (Shibuya)',
    stationProximity: 'JR 澀谷站 C2 出口直連 1 分鐘',
    isConvenientLocation: true,
    hotelRating: 9.0,
    hotelRatingText: '頂級奢華 (9.0/10)',
    roomType: '澀谷十字路口夜景雙人房',
    breakfastIncluded: true,
    flightDetail: '11/18 08:50 桃園飛 ➔ 11/23 14:15 成田回',
    hotelImg: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    directUrl: 'https://www.klook.com/zh-TW/',
    popularTag: '高奢網美旅宿 (高於27k門檻)',
    isAlertTarget: false // Exceeds 27000
  },
  {
    id: 'pkg-008',
    type: 'package',
    origin: 'KHH',
    originName: '高雄小港',
    destination: 'NRT',
    destinationName: '東京成田',
    airline: '台灣虎航 Tigerair',
    platform: 'agoda',
    platformName: 'Agoda 專案',
    price: 15800,
    originalPrice: 18500,
    hotelName: '千葉成田郊區微風膠囊旅店 (Breeze Inn Narita Outer)',
    hotelArea: '成田郊區 (非東京市區)',
    stationProximity: '公車站步行 12 分鐘 (需轉搭接駁車45分鐘至市區)',
    isConvenientLocation: false,
    hotelRating: 6.5,
    hotelRatingText: '普通 (6.5/10)',
    roomType: '單人膠囊臥鋪',
    breakfastIncluded: false,
    flightDetail: '11/18 08:00 高雄飛 ➔ 11/23 13:30 成田回',
    hotelImg: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
    directUrl: 'https://www.agoda.com/',
    popularTag: '極低價膠囊 (評分未達中等且非交通方便區域)',
    isAlertTarget: false // Low rating & bad location
  }
];

// 歷史價格走勢與未來趨勢資料 (過去30天至11/18前)
export const PRICE_TREND_DATA = {
  labels: ['10/19', '10/22', '10/25', '10/28', '10/31', '11/03', '11/06', '11/09', '11/12', '11/15', '今日(11/18)'],
  khhFlightAvg: [16800, 16200, 15900, 15500, 14800, 14200, 13800, 13200, 12900, 12800, 12800],
  tpeFlightAvg: [15900, 15500, 14900, 14200, 13800, 13200, 12900, 12400, 12100, 11900, 11900],
  pkgAvg: [26500, 25800, 24900, 24200, 23500, 22800, 21900, 20800, 19800, 18900, 18900]
};
